// Auto-generado desde comercial-v9.json — no editar manualmente.
export default {
  "metadata": {
    "contrato": "Contrato de Locación Comercial",
    "version": "V9_Monolitico_Desplegables_Estandarizados_AUDITADO_2026_09",
    "estado": "Produccion"
  },
  "document_settings": {
    "tipografia": "Times New Roman",
    "tamano_fuente": "11pt",
    "alineacion": "justify",
    "formato_markdown_permitido": false
  },
  "input_schema": {
    "locador": {
      "nombre_completo_required": "string",
      "dni_required": "string",
      "cuit_cuil_required": "string",
      "correo_electronico_required": "string",
      "domicilio_required": "string",
      "ciudad_required": "string",
      "departamento_partido_required": "string",
      "provincia_required": [
        "Buenos Aires",
        "Catamarca",
        "Chaco",
        "Chubut",
        "Córdoba",
        "Corrientes",
        "Entre Ríos",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuquén",
        "Río Negro",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Cruz",
        "Santa Fe",
        "Santiago del Estero",
        "Tierra del Fuego",
        "Tucumán"
      ]
    },
    "locatario": {
      "nombre_completo_required": "string",
      "dni_required": "string",
      "cuit_cuil_required": "string",
      "correo_electronico_required": "string",
      "domicilio_required": "string",
      "ciudad_required": "string",
      "departamento_partido_required": "string",
      "provincia_required": [
        "Buenos Aires",
        "Catamarca",
        "Chaco",
        "Chubut",
        "Córdoba",
        "Corrientes",
        "Entre Ríos",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuquén",
        "Río Negro",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Cruz",
        "Santa Fe",
        "Santiago del Estero",
        "Tierra del Fuego",
        "Tucumán"
      ]
    },
    "inmueble": {
      "calle_required": "string",
      "altura_required": "string",
      "piso_y_numero_local_required": "string",
      "nomenclatura_catastral_required": "string",
      "partida_inmobiliaria_required": "string",
      "destino_locacion_required": [
        "Gastronomía",
        "Oficina",
        "Consultorio",
        "Estudio jurídico",
        "Otro"
      ],
      "destino_otro_opcional": "string"
    },
    "plazo": {
      "cantidad_meses_numeros_required": "number",
      "cantidad_anos_numeros_required": "number",
      "inicio_dia_required": "string",
      "inicio_mes_required": [
        "enero",
        "febrero",
        "marzo",
        "abril",
        "mayo",
        "junio",
        "julio",
        "agosto",
        "septiembre",
        "octubre",
        "noviembre",
        "diciembre"
      ],
      "inicio_ano_required": "string",
      "fin_dia_required": "string",
      "fin_mes_required": [
        "enero",
        "febrero",
        "marzo",
        "abril",
        "mayo",
        "junio",
        "julio",
        "agosto",
        "septiembre",
        "octubre",
        "noviembre",
        "diciembre"
      ],
      "fin_ano_required": "string"
    },
    "condiciones_economicas": {
      "monto_mensual_letras_required": "string",
      "monto_mensual_numeros_required": "number_float",
      "periodo_primer_pago_required": [
        "mes",
        "bimestre",
        "trimestre",
        "semestre"
      ],
      "pago_desde_dia_required": "string",
      "pago_hasta_dia_required": "string",
      "porcentaje_interes_numeros_required": "number_float",
      "porcentaje_interes_letras_required": "string",
      "primer_dia_mora_required": "string",
      "ultimo_dia_condonacion_required": "string",
      "periodo_actualizacion_meses_required": "string",
      "indice_actualizacion_required": [
        "ICL",
        "IPC",
        "Otro"
      ],
      "indice_actualizacion_otro_opcional": "string",
      "dias_notificacion_rescision_required": "string",
      "dias_aviso_menor_rescision_required": "string",
      "meses_indemnizacion_menor_plazo_numeros_required": "string",
      "meses_indemnizacion_menor_plazo_letras_required": "string",
      "monto_deposito_letras_required": "string",
      "monto_deposito_numeros_required": "number_float",
      "dias_restitucion_deposito_required": "string",
      "parte_a_cargo_sellado_required": [
        "LOCATARIA",
        "LOCADORA"
      ]
    },
    "garantes": {
      "g1_nombre_opcional": "string",
      "g1_dni_opcional": "string",
      "g1_cuit_cuil_opcional": "string",
      "g1_correo_electronico_opcional": "string",
      "g1_domicilio_calle_opcional": "string",
      "g1_ciudad_opcional": "string",
      "g1_departamento_opcional": "string",
      "g1_provincia_opcional": [
        "Buenos Aires",
        "Catamarca",
        "Chaco",
        "Chubut",
        "Córdoba",
        "Corrientes",
        "Entre Ríos",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuquén",
        "Río Negro",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Cruz",
        "Santa Fe",
        "Santiago del Estero",
        "Tierra del Fuego",
        "Tucumán"
      ],
      "g1_nacionalidad_opcional": "string",
      "g2_texto_opcional": "string"
    },
    "cierre": {
      "centro_judicial_required": "string",
      "cantidad_ejemplares_letras_required": "string",
      "cantidad_ejemplares_numeros_required": "number",
      "ciudad_firma_required": "string",
      "departamento_firma_required": "string",
      "provincia_firma_required": [
        "Buenos Aires",
        "Catamarca",
        "Chaco",
        "Chubut",
        "Córdoba",
        "Corrientes",
        "Entre Ríos",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuquén",
        "Río Negro",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Cruz",
        "Santa Fe",
        "Santiago del Estero",
        "Tierra del Fuego",
        "Tucumán"
      ],
      "dia_firma_required": "string",
      "mes_firma_required": [
        "enero",
        "febrero",
        "marzo",
        "abril",
        "mayo",
        "junio",
        "julio",
        "agosto",
        "septiembre",
        "octubre",
        "noviembre",
        "diciembre"
      ],
      "ano_firma_required": "string"
    }
  },
  "logic_rules": [
    "IF true THEN render(contrato_integro_literal)"
  ],
  "template_blocks": {
    "contrato_integro_literal": "[CENTRAR]CONTRATO DE LOCACION COMERCIAL\n\nEntre {{locador.nombre_completo_required}}, Documento Nacional de Identidad número {{locador.dni_required}}, CUIL/T número {{locador.cuit_cuil_required}} correo electrónico: {{locador.correo_electronico_required}} con domiciliado en {{locador.domicilio_required}} de la ciudad {{locador.ciudad_required}} departamento/partido de {{locador.departamento_partido_required}} Provincia de {{locador.provincia_required}}, por una parte y en adelante LA PARTE LOCADORA y por la otra parte y en adelante LA PARTE LOCATARIA, {{locatario.nombre_completo_required}} Documento Nacional de Identidad número {{locatario.dni_required}} CUIT número {{locatario.cuit_cuil_required}}, correo electrónico: {{locatario.correo_electronico_required}} con domicilio en {{locatario.domicilio_required}}, de la ciudad {{locatario.ciudad_required}} departamento/partido de {{locatario.departamento_partido_required}} Provincia de {{locatario.provincia_required}}, convienen en celebrar el siguiente CONTRATO DE LOCACION sujeto a las cláusulas y condiciones que siguen:\n\nPRIMERA: objeto: La PARTE LOCADORA es propietaria de un local comercial ubicado sobre {{inmueble.calle_required}} nro. {{inmueble.altura_required}}, piso y número de local: {{inmueble.piso_y_numero_local_required}}, nomenclatura catastral {{inmueble.nomenclatura_catastral_required}}, partida inmobiliaria {{inmueble.partida_inmobiliaria_required}}. La parte locadora cede en este acto el uso y goce a título de LOCACIÓN a favor de la PARTE LOCATARIA el local comercial mencionado. Se alquilan asimismo los muebles que allí se encuentran y que se detallan en el anexo “ANEXO I- inventario”, que firman las partes y forma parte del presente contrato, donde se detallan los bienes muebles que se encuentran en el inmueble y su estado al momento de la celebración del contrato.\n\nSEGUNDA: permisos y habilitaciones: Será exclusiva responsabilidad de EL LOCATARIO: gestionar habilitaciones comerciales; obtener permisos municipales; cumplir normas bromatológicas, de seguridad e higiene; cumplir normativa laboral, impositiva y previsional; obtener autorizaciones administrativas necesarias para el giro comercial. EL LOCADOR no garantiza la aptitud administrativa o comercial del inmueble para la actividad pretendida por EL LOCATARIO.\n\nTERCERA: Plazo: El plazo de la locación se fija en {{plazo.cantidad_meses_numeros_required}} meses, es decir, {{plazo.cantidad_anos_numeros_required}} años, comenzando a regir a partir del {{plazo.inicio_dia_required}} del mes de {{plazo.inicio_mes_required}} del año {{plazo.inicio_ano_required}}, venciendo en consecuencia el día {{plazo.fin_dia_required}} del mes de {{plazo.fin_mes_required}} del año {{plazo.fin_ano_required}}, fecha en que deberá ser devuelto el inmueble, en las mismas condiciones en que la parte locataria la recibe y libre de ocupantes a la PARTE LOCADORA. La permanencia del LOCATARIO luego del vencimiento contractual no implicará renovación automática ni reconducción tácita, salvo acuerdo escrito entre las partes.\n\nCUARTA: Destino: El inmueble locado será destinado únicamente a {{inmueble.destino_locacion_required}} {{inmueble.destino_otro_opcional}}. El destino no podrá ser alterado durante la vigencia del contrato, sin conformidad previa y emanada por escrito de la parte locadora. El cambio o variación de este destino será considerado causa de resolución del contrato, con derecho para la PARTE LOCADORA de solicitar el desalojo del inmueble, con los daños y perjuicios pertinentes.\n\nQUINTA (Prohibición de Cesión): Queda expresamente prohibido ceder el presente contrato de locación, permutar, transferir, subarrendar o prestar total o parcialmente la propiedad, objeto de la presente, salvo autorización expresa de LA PARTE LOCADORA. La violación de estas prohibiciones dará lugar a la rescisión culposa del contrato y al desalojo correspondiente, además del pago de daños y perjuicios que resulten.\n\nSEXTA: obras y modificaciones: la PARTE LOCATARIA no podrá: realizar obras estructurales; alterar instalaciones esenciales; modificar fachadas; e intervenir muros portantes, sin autorización previa y escrita de LA PARTE LOCADORA. Las mejoras útiles o necesarias quedarán incorporadas al inmueble, salvo pacto en contrario.\n\nSÉPTIMA: Precio: El canon locativo mensual será la suma de {{condiciones_economicas.monto_mensual_letras_required}} (${{condiciones_economicas.monto_mensual_numeros_required}}) para el primer {{condiciones_economicas.periodo_primer_pago_required}}. Los cánones locativos se pagarán por mes adelantado del {{condiciones_economicas.pago_desde_dia_required}} al {{condiciones_economicas.pago_hasta_dia_required}} de cada mes, libre de gastos y servicios. Dichos importes serán abonados a la parte locadora o a quien designe oportunamente en su domicilio o en el lugar donde esta indique. El alquiler se pacta por periodo de mes entero y aunque LA PARTE LOCATARIA se mudará antes de finalizar el mes, pagará el alquiler correspondiente a ese mes en forma íntegra. La mora se producirá automáticamente por el mero vencimiento del plazo de pago.\n\nOCTAVA: intereses: La falta de pago del alquiler en tiempo y forma hará incurrir a la PARTE LOCATARIA en mora automática, pactándose un interés mensual del {{condiciones_economicas.porcentaje_interes_numeros_required}}% ({{condiciones_economicas.porcentaje_interes_letras_required}}) desde el primer día de atraso, es decir desde el día {{condiciones_economicas.primer_dia_mora_required}}. En el supuesto que la PARTE LOCATARIA cancele el pago del alquiler hasta el {{condiciones_economicas.ultimo_dia_condonacion_required}} día de cada mes, la PARTE LOCADORA se obliga en forma irrevocable a condonar los intereses que se hubiesen generado por dicho período locativo.\n\nNOVENA: actualización del precio: El canon locativo será actualizado cada {{condiciones_economicas.periodo_actualizacion_meses_required}} meses, conforme al siguiente mecanismo: {{condiciones_economicas.indice_actualizacion_required}} {{condiciones_economicas.indice_actualizacion_otro_opcional}}. La actualización será automática y no requerirá interpelación previa.\n\nDÉCIMA: Rescisión Anticipada: La PARTE LOCATARIA podrá rescindir el presente Contrato de Locación transcurridos los primeros seis (6) meses de plazo del contrato, sin expresión de causa y en forma anticipada, bastando para ello, hacer saber su voluntad en tal sentido a la PARTE LOCADORA, por medio fehaciente con una antelación no menor a {{condiciones_economicas.dias_notificacion_rescision_required}} días respecto de la fecha prevista en que restituirán lo arrendado. De esta manera la PARTE LOCATARIA no deberán pagar suma alguna en concepto de indemnización, pero si la antelación es menor a los {{condiciones_economicas.dias_aviso_menor_rescision_required}} días, en tal caso, la PARTE LOCATARIA deberá pagar a la PARTE LOCADORA, en concepto de única y definitiva indemnización por la resolución anticipada, una cantidad de dinero igual a {{condiciones_economicas.meses_indemnizacion_menor_plazo_numeros_required}} ({{condiciones_economicas.meses_indemnizacion_menor_plazo_letras_required}}) del precio del alquiler, si la rescisión se produce dentro del primer 1º año del plazo y de un 1 (un) mes del precio del alquiler si la rescisión se produce con posterioridad al primer año.\n\nDÉCIMO PRIMERA: expensas, impuestos y servicios: Serán a cargo de la PARTE LOCATARIA: expensas ordinarias; servicios; tasas comerciales; habilitaciones; tributos vinculados al uso y actividad comercial. Serán a cargo de la PARTE LOCADORA: impuestos sobre la propiedad; expensas extraordinarias; contribuciones extraordinarias.\n\nDÉCIMO SEGUNDA: reparación y mantenimiento: Serán a cargo de la PARTE LOCATARIA: mantenimiento ordinario; reparaciones derivadas del uso comercial; daños ocasionados por personal, clientes o proveedores; adecuaciones necesarias para la actividad. Serán a cargo de la PARTE LOCADORA: reparaciones estructurales ajenas al uso comercial; vicios preexistentes no aparentes; deterioros no imputables a la PARTE LOCATARIA.\n\nDÉCIMO TERCERA: seguros: la PARTE LOCATARIA deberá contratar y mantener vigente durante toda la locación: seguro contra incendio; seguro de responsabilidad civil; cualquier otro seguro exigido por normativa aplicable. La PARTE LOCADORA podrá requerir constancia de vigencia en cualquier momento.\n\nDÉCIMO CUARTA: depósito en garantía: la PARTE LOCATARIA entrega en este acto la suma de {{condiciones_economicas.monto_deposito_letras_required}} (${{condiciones_economicas.monto_deposito_numeros_required}}) en concepto de depósito de garantía. La PARTE LOCADORA podrá imputar dicho depósito a alquileres impagos; servicios adeudados; daños al inmueble; incumplimientos contractuales; faltantes de inventario. El saldo remanente será restituido dentro del plazo de {{condiciones_economicas.dias_restitucion_deposito_required}} días corridos desde la efectiva restitución del inmueble.\n\nDÉCIMO QUINTA: responsabilidad: La PARTE LOCATARIA será exclusivamente responsable frente a terceros, empleados, clientes, organismos públicos y autoridades administrativas por las consecuencias derivadas de su actividad comercial. La PARTE LOCADORA no responderá por: interrupciones de servicios públicos; daños derivados de la actividad comercial; pérdidas comerciales; lucro cesante de la PARTE LOCATARIA.\n\nDÉCIMO SEXTA: inspección: la PARTE LOCADORA y/o la inmobiliaria se reservan el derecho de inspeccionar el inmueble en forma periódica, previo aviso razonable a la PARTE LOCATARIA, debiendo la PARTE LOCATARIA comunicarle cualquier daño o desperfecto que se produzca en el mismo dentro de las cuarenta y ocho (48hs.) horas de ocurrido.\n\nDÉCIMO SÉPTIMA: Garantía: Presentes en este acto, el señor/los señores {{garantes.g1_nombre_opcional}} DNI número {{garantes.g1_dni_opcional}} CUIT número {{garantes.g1_cuit_cuil_opcional}} correo electrónico: {{garantes.g1_correo_electronico_opcional}} con domicilio en calle {{garantes.g1_domicilio_calle_opcional}} de la ciudad de {{garantes.g1_ciudad_opcional}} del departamento/partido de {{garantes.g1_departamento_opcional}} de la provincia de {{garantes.g1_provincia_opcional}} de nacionalidad {{garantes.g1_nacionalidad_opcional}}, mayor de edad, {{garantes.g2_texto_opcional}} declara/n conocer el contenido de este contrato en todas sus partes y asume/n por el presente el carácter de garante/s solidario/s liso/s y llano/s y principal/es pagador/es por todos los alquileres e indemnizaciones, todas y cada una de las obligaciones asumidas por la parte LOCATARIA en este contrato, renunciando al beneficio de excusión y al beneficio de división, hasta que la PARTE LOCADORA sea restituida de la propiedad, libre de ocupantes y en las condiciones pactadas. Comprende los gastos y costas de los juicios que se dedujeren contra su garantido y hasta la cancelación total de las obligaciones correspondientes.\n\nDÉCIMO OCTAVA: restitución del inmueble: Al finalizar el contrato EL LOCATARIO deberá: restituir el inmueble libre de ocupantes y bienes; entregar llaves; devolver el inmueble en adecuado estado de conservación; acreditar cancelación de servicios, tasas y expensas.\n\nDÉCIMO NOVENA: domicilio electrónico: Las partes constituyen como domicilios electrónicos válidos los correos electrónicos denunciados en el presente contrato.\n\nVIGÉSIMA: Domicilios y Jurisdicción: Para todos los efectos, tanto legales como judiciales o extrajudiciales, que se deriven de este contrato las partes se someten a la jurisdicción de los Tribunales Ordinarios de {{cierre.centro_judicial_required}} siempre que resulte legalmente competente, siendo validas las notificaciones que se realicen en los domicilios indicados en el encabezamiento del presente contrato. Las partes contratantes hacen expresa renuncia al Fuero Federal y constituyen domicilios especiales para todos los efectos legales, judiciales o extrajudiciales los que se enuncian en este instrumento.\n\nVIGÉSIMO PRIMERA: sellado: Es a cargo de la PARTE {{condiciones_economicas.parte_a_cargo_sellado_required}} el gasto que genere el presente instrumento en carácter de impuesto de sellos y certificaciones de firmas.\n\nVIGÉSIMO SEGUNDA: firmas e instrumentación: 1. Se suscriben {{cierre.cantidad_ejemplares_letras_required}} ({{cierre.cantidad_ejemplares_numeros_required}}) ejemplares iguales de este CONTRATO, a un solo efecto. 2. En este mismo acto, la PARTE LOCATARIA recibe las llaves y la tenencia de la UNIDAD LOCADA.\n\nVIGÉSIMO TERCERA: lugar y fecha: Celebrado en la Ciudad de {{cierre.ciudad_firma_required}}, departamento/partido de {{cierre.departamento_firma_required}}, en la provincia de {{cierre.provincia_firma_required}} a los días {{cierre.dia_firma_required}} de {{cierre.mes_firma_required}} del año {{cierre.ano_firma_required}}."
  }
};
